version: '3.8'

services:
  ciris-wyoming:
    build: .
    container_name: ciris-wyoming-bridge
    restart: unless-stopped
    ports:
      - "10300:10300"
    environment:
      - STT_API_KEY=${STT_API_KEY}
      - TTS_API_KEY=${TTS_API_KEY}
      - CIRIS_API_KEY=${CIRIS_API_KEY}
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    depends_on:
      - ciris
    networks:
      - ciris-network

  ciris:
    image: ciris/agent:latest
    container_name: ciris-agent
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: --mode api --profile home_assistant
    networks:
      - ciris-network

networks:
  ciris-network:
    driver: bridge
