# Dependabot configuration for CIRISHome
# Keeps dependencies updated automatically

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "emoore"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️ dev"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/homeassistant-ciris"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "emoore"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "⬆️ docker"
      include: "scope"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "emoore"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "⬆️ actions"
      include: "scope"
