"""CIRIS Agent Docker deployment and configuration.

Handles:
1. Token persistence to .env
2. Docker image deployment
3. Jetson Nano LLM configuration
"""

import json
import logging
import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

# Default configuration
DEFAULT_CONFIG = {
    "jetson_ip": "",
    "jetson_port": 11434,
    "llm_model": "gemma3:4b-it-q4_K_M",  # Gemma 4 smallest Q4
    "ha_url": "",
    "ha_token": "",
    "ha_refresh_token": "",
}


@dataclass
class CIRISConfig:
    """CIRIS Home configuration."""

    ha_url: str
    ha_token: str
    ha_refresh_token: str
    jetson_ip: str = ""
    jetson_port: int = 11434
    llm_model: str = "gemma3:4b-it-q4_K_M"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "ha_url": self.ha_url,
            "ha_token": self.ha_token,
            "ha_refresh_token": self.ha_refresh_token,
            "jetson_ip": self.jetson_ip,
            "jetson_port": self.jetson_port,
            "llm_model": self.llm_model,
        }


def get_config_dir() -> Path:
    """Get CIRIS configuration directory.

    Creates ~/.ciris if it doesn't exist.
    """
    config_dir = Path.home() / ".ciris"
    config_dir.mkdir(parents=True, exist_ok=True)
    return config_dir


def get_config_path() -> Path:
    """Get path to config.json."""
    return get_config_dir() / "config.json"


def load_config() -> Optional[CIRISConfig]:
    """Load configuration from disk."""
    config_path = get_config_path()
    if not config_path.exists():
        return None

    try:
        with open(config_path) as f:
            data = json.load(f)
            return CIRISConfig(
                ha_url=data.get("ha_url", ""),
                ha_token=data.get("ha_token", ""),
                ha_refresh_token=data.get("ha_refresh_token", ""),
                jetson_ip=data.get("jetson_ip", ""),
                jetson_port=data.get("jetson_port", 11434),
                llm_model=data.get("llm_model", DEFAULT_CONFIG["llm_model"]),
            )
    except Exception as e:
        logger.error(f"Failed to load config: {e}")
        return None


def save_config(config: CIRISConfig) -> bool:
    """Save configuration to disk."""
    config_path = get_config_path()

    try:
        with open(config_path, "w") as f:
            json.dump(config.to_dict(), f, indent=2)
        logger.info(f"Configuration saved to {config_path}")
        return True
    except Exception as e:
        logger.error(f"Failed to save config: {e}")
        return False


def generate_env_file(config: CIRISConfig, output_path: Path) -> bool:
    """Generate .env file for Docker deployment.

    Args:
        config: CIRIS configuration
        output_path: Path to write .env file

    Returns:
        True if successful
    """
    env_content = f"""# CIRIS Home Configuration
# Generated by ciris-home CLI

# Home Assistant
HOME_ASSISTANT_URL={config.ha_url}
HOME_ASSISTANT_TOKEN={config.ha_token}
HOME_ASSISTANT_REFRESH_TOKEN={config.ha_refresh_token}

# Jetson Nano LLM
JETSON_NANO_IP={config.jetson_ip}
JETSON_NANO_PORT={config.jetson_port}
LLM_MODEL={config.llm_model}

# CIRIS Engine OpenAI-compatible API (pointing to Jetson)
OPENAI_API_KEY=jetson-local-llm
OPENAI_API_BASE=http://{config.jetson_ip}:{config.jetson_port}/v1
OPENAI_MODEL_NAME={config.llm_model}

# Safety acknowledgments
RESPONSIBILITY_ACCEPTED=true
I_ACCEPT_HOME_AUTOMATION_RESPONSIBILITY=true

# Privacy settings
LOCAL_PROCESSING_ONLY=true
MEDICAL_GRADE_PRIVACY=true
"""

    try:
        with open(output_path, "w") as f:
            f.write(env_content)
        logger.info(f".env file written to {output_path}")
        return True
    except Exception as e:
        logger.error(f"Failed to write .env file: {e}")
        return False


def check_docker() -> bool:
    """Check if Docker is available."""
    try:
        result = subprocess.run(
            ["docker", "--version"],
            capture_output=True,
            text=True,
        )
        return result.returncode == 0
    except FileNotFoundError:
        return False


def check_docker_compose() -> bool:
    """Check if Docker Compose is available."""
    # Try docker compose (v2)
    try:
        result = subprocess.run(
            ["docker", "compose", "version"],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return True
    except FileNotFoundError:
        pass

    # Try docker-compose (v1)
    try:
        result = subprocess.run(
            ["docker-compose", "--version"],
            capture_output=True,
            text=True,
        )
        return result.returncode == 0
    except FileNotFoundError:
        return False


def pull_ciris_image(tag: str = "latest") -> bool:
    """Pull the CIRIS agent Docker image.

    Args:
        tag: Image tag to pull

    Returns:
        True if successful
    """
    image = f"ghcr.io/cirisai/ciris-agent:{tag}"
    print(f"Pulling CIRIS agent image: {image}")

    try:
        result = subprocess.run(
            ["docker", "pull", image],
            capture_output=False,
        )
        return result.returncode == 0
    except Exception as e:
        logger.error(f"Failed to pull image: {e}")
        return False


def start_ciris_container(
    config: CIRISConfig,
    work_dir: Path,
    detach: bool = True,
) -> bool:
    """Start the CIRIS agent container.

    Args:
        config: CIRIS configuration
        work_dir: Working directory with docker-compose.yml
        detach: Run in detached mode

    Returns:
        True if successful
    """
    # Generate .env file
    env_path = work_dir / ".env"
    if not generate_env_file(config, env_path):
        return False

    # Check for docker-compose.yml
    compose_file = work_dir / "docker-compose.yml"
    if not compose_file.exists():
        logger.error(f"docker-compose.yml not found at {compose_file}")
        return False

    # Start container
    cmd = ["docker", "compose", "up"]
    if detach:
        cmd.append("-d")

    try:
        result = subprocess.run(
            cmd,
            cwd=work_dir,
            capture_output=False,
        )
        return result.returncode == 0
    except Exception as e:
        logger.error(f"Failed to start container: {e}")
        return False


def discover_jetson() -> Optional[str]:
    """Discover Jetson Nano on the network.

    Returns:
        Jetson IP address if found, None otherwise
    """
    import asyncio
    import socket

    hostnames = [
        "jetson.local",
        "jetson-nano.local",
        "nano.local",
    ]

    for hostname in hostnames:
        try:
            ip = socket.gethostbyname(hostname)
            # Verify Ollama is running
            import aiohttp

            async def check_ollama():
                try:
                    timeout = aiohttp.ClientTimeout(total=2)
                    async with aiohttp.ClientSession(timeout=timeout) as session:
                        async with session.get(f"http://{ip}:11434/api/tags") as resp:
                            if resp.status == 200:
                                return ip
                except Exception:
                    pass
                return None

            result = asyncio.get_event_loop().run_until_complete(check_ollama())
            if result:
                return result

        except socket.gaierror:
            continue

    return None


async def list_ollama_models_async(jetson_ip: str, port: int = 11434) -> list:
    """List available models on Jetson Ollama (async version).

    Args:
        jetson_ip: Jetson IP address
        port: Ollama port

    Returns:
        List of model names
    """
    import aiohttp

    try:
        timeout = aiohttp.ClientTimeout(total=5)
        async with aiohttp.ClientSession(timeout=timeout) as session:
            async with session.get(f"http://{jetson_ip}:{port}/api/tags") as resp:
                if resp.status == 200:
                    data = await resp.json()
                    return [m["name"] for m in data.get("models", [])]
    except Exception as e:
        logger.error(f"Failed to list models: {e}")
    return []


def list_ollama_models(jetson_ip: str, port: int = 11434) -> list:
    """List available models on Jetson Ollama (sync wrapper).

    Args:
        jetson_ip: Jetson IP address
        port: Ollama port

    Returns:
        List of model names
    """
    import requests

    try:
        resp = requests.get(f"http://{jetson_ip}:{port}/api/tags", timeout=5)
        if resp.status_code == 200:
            data = resp.json()
            return [m["name"] for m in data.get("models", [])]
    except Exception as e:
        logger.error(f"Failed to list models: {e}")
    return []
