# CIRIS Voice Wyoming Bridge Configuration
# Copy to config.yaml and update with your settings

# Wyoming server settings
wyoming:
  host: "0.0.0.0"
  port: 10300
  # Extended pipeline timeout support
  timeout: 60

# CIRIS API settings
ciris:
  # API endpoint
  api_url: "http://localhost:8080"

  # Authentication (use one of these methods)
  # Option 1: API key
  api_key: ""  # Or use CIRIS_API_KEY env var

  # Option 2: Username/password (if not using API key)
  # username: "voice_user"
  # password: "voice_password"

  # Extended timeout for complex queries (just under HA's 60s)
  timeout: 58

  # Channel identification
  channel_id: "wyoming_default"

  # Voice profile (for personalization)
  profile: "default"

  # Language for voice context
  language: "en-US"

# Speech-to-Text settings
stt:
  # Provider: "openai" or "google"
  provider: "openai"

  # OpenAI settings
  openai_api_key: ""  # Or use OPENAI_API_KEY env var
  model: "whisper-1"
  language: "en"

  # Google Cloud settings (if using google provider)
  # google_credentials_path: "/config/google_cloud_key.json"
  # google_language_code: "en-US"
  # google_model: "latest_long"

# Text-to-Speech settings
tts:
  # Provider: "openai" or "google"
  provider: "openai"

  # OpenAI settings
  model: "tts-1"
  voice: "nova"  # Options: alloy, echo, fable, onyx, nova, shimmer
  speed: 1.0

  # Google Cloud settings (if using google provider)
  # google_credentials_path: "/config/google_cloud_key.json"
  # google_language_code: "en-US"
  # google_voice_name: "en-US-Chirp3-HD-Achernar"  # High-quality Chirp3 voice
  # google_speaking_rate: 1.0
  # google_pitch: 0.0

# Logging settings
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Development settings
development:
  # Skip SSL verification (for local development only)
  ssl_verify: true

  # Enable debug mode
  debug: false

  # Save audio files for debugging
  save_audio: false
  audio_dir: "./debug_audio"
