build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.18"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.11-alpine3.18"
labels:
  org.opencontainers.image.title: "CIRIS Wyoming Bridge"
  org.opencontainers.image.description: "Connect CIRIS AI to Home Assistant Voice"
  org.opencontainers.image.source: "https://github.com/yourusername/ciris-wyoming-addon"
  org.opencontainers.image.licenses: "Apache-2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
